services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: go run main.go
    depends_on:
      - postgresdb
    links:
      - postgresdb
      
  postgresdb:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "15432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: